### ISSUE TITLE
applying diff to a large file cause out of memory

### ISSUE THREAD

**Issue by JoaoBGusmao** [dchest/fossil-delta-js#2]
I'm trying to apply a 10mb diff to a 600mb file. The problem is when I try to apply the diff. I load both files then pass it to the apply method, and it throw an exception:
`<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000017092F373A9 <JS Object>
    2: apply [F:\file\patcher-builder\node_modules\fossil-delta\fossi
l-delta.js:~396] [pc=000000C005DA05F0] (this=0000006BFEE6B6D9 <an Object with ma
p 000001EAC7731759>,src=0000017092FB7E61 <an Uint8Array with map 000001EAC771D0C
9>,delta=0000017092F3D309 <an Uint8Array with map 000001EAC771D0C9>,opts=0000017
092F04131 <undefined>)
    3: arguments adaptor frame: 2->3
    4: /* anony...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory`

My code is the following:
```
function run() {
	var fileName = 'teste.file'; //600mb file
	var diffName = '4b0962cc0446643e545eaa01bd844f1d'; //dif file

	const originalFile = new Promise( resolve => {
		return fileToBuffer( './test/' + fileName, function( e, f0 ) {
			resolve(f0);
		})
	});

	const patchFile = new Promise( resolve => {
		return fileToBuffer( './test/' + diffName, function( e, f0 ) {
			resolve( f0 );
		})
	});
	
	Promise.all( [ originalFile, patchFile ] ).then( result => {
		var newFile = nDelta.apply( result[ 0 ], result[ 1 ] );
		var final   = new Buffer( newFile );
		fs.writeFile( './test/' + '_' + fileName, newFile, () => {
		});
	});
}
function fileToBuffer( fileName, cb ) {
	var readStream = fs.createReadStream( fileName );
	var chunks = [];
	
	readStream.on('error', err => {
		return cb( err );
	});

	readStream.on('data', chunk => {
		chunks.push( chunk );
	});

	readStream.on('close', () => {
		return cb( null, Buffer.concat( chunks ) );
	});
}


run();
```

I've tested with 'node-delta' package and it seens to be working fine, but I can't use it due to some compiling erros on the final project

**Comment by dchest** [comment]
Indeed, Node just ran out of memory it can hold — there's 600 MB array that `apply` returns and then you allocate additional 600 MB buffer.

I can only suggest that you split the file into smaller chunks and apply delta compression to each chunk or use a some other delta compression implementation that uses streams to process files in chunks instead of holding the whole file contents in memory.
